# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/patrick/picocoap

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/patrick/picocoap

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/patrick/picocoap/CMakeFiles /home/patrick/picocoap/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/patrick/picocoap/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named picocoap-client_generated_modality_probe_mutators

# Build rule for target.
picocoap-client_generated_modality_probe_mutators: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 picocoap-client_generated_modality_probe_mutators
.PHONY : picocoap-client_generated_modality_probe_mutators

# fast build rule for target.
picocoap-client_generated_modality_probe_mutators/fast:
	$(MAKE) -f CMakeFiles/picocoap-client_generated_modality_probe_mutators.dir/build.make CMakeFiles/picocoap-client_generated_modality_probe_mutators.dir/build
.PHONY : picocoap-client_generated_modality_probe_mutators/fast

#=============================================================================
# Target rules for targets named picocoap-client_generated_modality_probe_manifest

# Build rule for target.
picocoap-client_generated_modality_probe_manifest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 picocoap-client_generated_modality_probe_manifest
.PHONY : picocoap-client_generated_modality_probe_manifest

# fast build rule for target.
picocoap-client_generated_modality_probe_manifest/fast:
	$(MAKE) -f CMakeFiles/picocoap-client_generated_modality_probe_manifest.dir/build.make CMakeFiles/picocoap-client_generated_modality_probe_manifest.dir/build
.PHONY : picocoap-client_generated_modality_probe_manifest/fast

#=============================================================================
# Target rules for targets named picocoap-client

# Build rule for target.
picocoap-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 picocoap-client
.PHONY : picocoap-client

# fast build rule for target.
picocoap-client/fast:
	$(MAKE) -f CMakeFiles/picocoap-client.dir/build.make CMakeFiles/picocoap-client.dir/build
.PHONY : picocoap-client/fast

#=============================================================================
# Target rules for targets named picocoap-client_generated_modality_probe_header

# Build rule for target.
picocoap-client_generated_modality_probe_header: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 picocoap-client_generated_modality_probe_header
.PHONY : picocoap-client_generated_modality_probe_header

# fast build rule for target.
picocoap-client_generated_modality_probe_header/fast:
	$(MAKE) -f CMakeFiles/picocoap-client_generated_modality_probe_header.dir/build.make CMakeFiles/picocoap-client_generated_modality_probe_header.dir/build
.PHONY : picocoap-client_generated_modality_probe_header/fast

#=============================================================================
# Target rules for targets named picocoap

# Build rule for target.
picocoap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 picocoap
.PHONY : picocoap

# fast build rule for target.
picocoap/fast:
	$(MAKE) -f CMakeFiles/picocoap.dir/build.make CMakeFiles/picocoap.dir/build
.PHONY : picocoap/fast

examples/posix/client.o: examples/posix/client.c.o

.PHONY : examples/posix/client.o

# target to build an object file
examples/posix/client.c.o:
	$(MAKE) -f CMakeFiles/picocoap-client.dir/build.make CMakeFiles/picocoap-client.dir/examples/posix/client.c.o
.PHONY : examples/posix/client.c.o

examples/posix/client.i: examples/posix/client.c.i

.PHONY : examples/posix/client.i

# target to preprocess a source file
examples/posix/client.c.i:
	$(MAKE) -f CMakeFiles/picocoap-client.dir/build.make CMakeFiles/picocoap-client.dir/examples/posix/client.c.i
.PHONY : examples/posix/client.c.i

examples/posix/client.s: examples/posix/client.c.s

.PHONY : examples/posix/client.s

# target to generate assembly for a file
examples/posix/client.c.s:
	$(MAKE) -f CMakeFiles/picocoap-client.dir/build.make CMakeFiles/picocoap-client.dir/examples/posix/client.c.s
.PHONY : examples/posix/client.c.s

generated_mutators/send_skip.o: generated_mutators/send_skip.c.o

.PHONY : generated_mutators/send_skip.o

# target to build an object file
generated_mutators/send_skip.c.o:
	$(MAKE) -f CMakeFiles/picocoap-client.dir/build.make CMakeFiles/picocoap-client.dir/generated_mutators/send_skip.c.o
.PHONY : generated_mutators/send_skip.c.o

generated_mutators/send_skip.i: generated_mutators/send_skip.c.i

.PHONY : generated_mutators/send_skip.i

# target to preprocess a source file
generated_mutators/send_skip.c.i:
	$(MAKE) -f CMakeFiles/picocoap-client.dir/build.make CMakeFiles/picocoap-client.dir/generated_mutators/send_skip.c.i
.PHONY : generated_mutators/send_skip.c.i

generated_mutators/send_skip.s: generated_mutators/send_skip.c.s

.PHONY : generated_mutators/send_skip.s

# target to generate assembly for a file
generated_mutators/send_skip.c.s:
	$(MAKE) -f CMakeFiles/picocoap-client.dir/build.make CMakeFiles/picocoap-client.dir/generated_mutators/send_skip.c.s
.PHONY : generated_mutators/send_skip.c.s

src/coap.o: src/coap.c.o

.PHONY : src/coap.o

# target to build an object file
src/coap.c.o:
	$(MAKE) -f CMakeFiles/picocoap.dir/build.make CMakeFiles/picocoap.dir/src/coap.c.o
.PHONY : src/coap.c.o

src/coap.i: src/coap.c.i

.PHONY : src/coap.i

# target to preprocess a source file
src/coap.c.i:
	$(MAKE) -f CMakeFiles/picocoap.dir/build.make CMakeFiles/picocoap.dir/src/coap.c.i
.PHONY : src/coap.c.i

src/coap.s: src/coap.c.s

.PHONY : src/coap.s

# target to generate assembly for a file
src/coap.c.s:
	$(MAKE) -f CMakeFiles/picocoap.dir/build.make CMakeFiles/picocoap.dir/src/coap.c.s
.PHONY : src/coap.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... picocoap-client_generated_modality_probe_mutators"
	@echo "... edit_cache"
	@echo "... picocoap-client_generated_modality_probe_manifest"
	@echo "... picocoap-client"
	@echo "... picocoap-client_generated_modality_probe_header"
	@echo "... picocoap"
	@echo "... examples/posix/client.o"
	@echo "... examples/posix/client.i"
	@echo "... examples/posix/client.s"
	@echo "... generated_mutators/send_skip.o"
	@echo "... generated_mutators/send_skip.i"
	@echo "... generated_mutators/send_skip.s"
	@echo "... src/coap.o"
	@echo "... src/coap.i"
	@echo "... src/coap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

